### ISSUE TITLE
Facial recognition technology for welfare

### ISSUE THREAD

**Issue by audas** [mdavis-xyz/mdavis.xyz#1]
https://www-dailymail-co-uk.cdn.ampproject.org/v/s/www.dailymail.co.uk/news/article-8783517/amp/Australian-government-introduces-250million-facial-recognition-access-Centrelink-benefits-dole.html?usqp=mq331AQFKAGwASA%3D&amp_js_v=0.1#referrer=https%3A%2F%2Fwww.google.com&amp_tf=From%20%251%24s&ampshare=https%3A%2F%2Fwww.dailymail.co.uk%2Fnews%2Farticle-8783517%2FAustralian-government-introduces-250million-facial-recognition-access-Centrelink-benefits-dole.html

**Comment by mdavis-xyz** [comment]
noted, I'll add it when I get a chance

**Comment by mdavis-xyz** [comment]
Non AMP link: https://www.dailymail.co.uk/news/article-8783517

**Comment by mdavis-xyz** [comment]
It's now in the draft list. Will be published later today.
