### ISSUE TITLE
Achievements of the Coalition Government - Update

### ISSUE THREAD

**Issue by kompuda** [mdavis-xyz/mdavis.xyz#10]
Hi Matthew,
I stumbled across some of your work including the Achievements of the Coalition Govt page. I was wondering if you have thought about updating it given an election will be coming in the next 12 months or so.
Reason I ask is that I am working with the Steering Committee for the Voices of Kooyong. Voices groups have sprung up all over the country. We're a grass roots political group with the express intent to oust Josh Frydenberg from his cosy "safe"seat. We believe not only us the residents of this electorate but more broadly the people of Australia deserve a better Treasurer, one with a heart and conscience and also to stop his leadership aspirations. It'll take a 7% swing but its not impossible.
The list is a great reference, I hope you don't mind us utilizing it for our research. I'm sure we can send out links to it via our social media channels. 
I'm wondering how did you collate the original list? Surely it wasn't keeping a diary? 
Cheers,
Chris MacKellar
chrismackellar@gmail.com

**Comment by mdavis-xyz** [comment]
Hi,

Yes I'm still maintaining the list.

I dont update it frequently. Rather, when I see stuff in the news I pop the URL into a note app on my phone. Then once every 2 or 3 months I go through that list and update this git repo.

Currently I've got two dozen dots to be added. Feel free to suggest specific additions if you notice anything missing.
