### ISSUE TITLE
Header Graphic

### ISSUE THREAD

**Issue by kyteflyer** [mdavis-xyz/mdavis.xyz#11]
Just wondering if its time to update the header graphic on https://www.mdavis.xyz/govlist/ to more accurately reflect the 2021 government incompetents?

**Comment by mdavis-xyz** [comment]
Good idea.

The website has got quite popular since I copy-pasted the original image from somewhere. I should probably be legit about the copywrite. Any idea where to get an image I'm allowed to use?

I found one on Getty Images, but they charge $500. That's way too much.
Most images on Wikipedia can be re-used. I haven't found any suitable ones though.

**Comment by kyteflyer** [comment]
How about a photo of Scummo with a bushfire as a background.  You could add Taylor and McKenzie too :)  I see most of the gfx used on independentaustralia.net, michaelwest.com and others are cobbled together in that way :)

cheers
Sue

**Comment by mdavis-xyz** [comment]
Good idea, although I don't want the photo to be too opinionated or partisan. I want people who like the Liberals to read the article, and not be turned away by the photo. Perhaps flames as a background will deter them.

I've found that AAP sells reasonable priced photos, and unlike Getty they don't seem unethical. The trouble is that all the recent ones have at most one maskless person.

I particularly like this one:
https://www.pedestrian.tv/news/scott-morrison-says-he-wants-tony-abbott-back-in-government/
But that's so old that Dutton still has some hair. 
Should I have something more recent?
I am leaning towards an older photo, to emphasise how this is across multiple PMs and multiple election cycles.

Like this one?
https://photos-cdn.aap.com.au/Image/20150209001100242079?path=/aap_dev4/device/imagearc/2015/02-09/77/c1/ae/aapimage-6j58wolwvb6p1k5sl58_layout.jpg
20150209001100242079

https://photos-cdn.aap.com.au/Preview/20150319001113245845?assetType=IMAGE&path=/aap_dev16/device/imagearc/2015/03-19/3e/a5/2d/aapimage-6joutmdu4k47228sn7r_minihighres.jpg
20150319001113245845

https://photos-cdn.aap.com.au/Preview/20150319001113263934?assetType=IMAGE&path=/aap_dev16/device/imagearc/2015/03-19/fe/0b/7d/aapimage-6jove45u2mt1g0z54cr3_minihighres.jpg
20150319001113263934

https://photos-cdn.aap.com.au/Preview/20191107001431339894?assetType=IMAGE&path=/aap_dev19/device/imagearc/2019/11-07/c8/e0/17/aapimage-77vdcmklc84gz17agur_minihighres.jpg
20191107001431339894

Here are some other photos (mostly notes to myself):

https://photos-cdn.aap.com.au/Image/20220216001624677120?path=/aap_dev15/device/imagearc/2022/02-16/19/6e/0a/aapimage-7jqsejdc411mfuu41lo7_layout.jpg
20220216001624677120

https://photos-cdn.aap.com.au/Image/20220216001624677929?path=/aap_dev15/device/imagearc/2022/02-16/5a/d8/2c/aapimage-7jqsf6yjspjcd74e1lo7_layout.jpg
20220216001624677929

https://photos-cdn.aap.com.au/Image/20220215001623964327?path=/aap_dev15/device/imagearc/2022/02-15/18/41/1e/aapimage-7jqacoweeb4dpm2zmao_layout.jpg
20220215001623964327

https://photos-cdn.aap.com.au/Image/20220215001623893707?path=/aap_dev15/device/imagearc/2022/02-15/11/f4/9f/aapimage-7jq8lxid6o4138hosmao_layout.jpg
20220215001623893707

https://photos-cdn.aap.com.au/Image/20220209001621573115?path=/aap_dev15/device/imagearc/2022/02-09/8e/b6/08/aapimage-7jn6sljautg1amlgmmao_layout.jpg
 20220209001621573115

https://photos-cdn.aap.com.au/Image/20180824001358469134?path=/aap_dev11/device/imagearc/2018/08-24/07/af/1d/aapimage-71l81hq60evtwjgb92e_layout2.jpg

**Comment by kyteflyer** [comment]
hmmm . I liked the idea of your first, have you access to a shot of Dutton, Morrison, Taylor, Cash and McKenzie?  That would serve well

**Comment by mdavis-xyz** [comment]
Updated
