### ISSUE TITLE
Readability of Numbered Lists

### ISSUE THREAD

**Issue by SirJaymie** [mdavis-xyz/mdavis.xyz#12]
Hey. I've been struggling to read the numbered lists on the govlist. Would you consider addressing this, maybe by adding white-space or padding between each numbered item please?

I made a minor change by adding white-space (specifically, testing by adding padding-top: 20px to li locally in browser) and I feel it's made a difference to readability.

Before
![image](https://user-images.githubusercontent.com/11805666/121990229-c36cfc00-cde0-11eb-80a1-79b2d65a6e14.png)

After
![image](https://user-images.githubusercontent.com/11805666/121990198-b8b26700-cde0-11eb-8755-faeb84fcbb20.png)

Thanks for your time!

**Comment by mdavis-xyz** [comment]
Ok I've added that change. Is that enough spacing, or do you think there should be more?
