### ISSUE TITLE
Change

### ISSUE THREAD

**Issue by np182** [mdavis-xyz/mdavis.xyz#14]
<img width="355" alt="Screen Shot 2021-07-18 at 8 04 13 pm" src="https://user-images.githubusercontent.com/87623775/126086353-708b2aba-766a-45c6-b291-1d0a3279bed9.png">

Hi Matthew - not sure if you can change (or hide) this but the "May 11 2019" posted here is a little misleading and makes the page look like it's not been updated (even though it has). 

Are you able to either change that to date last updated, or, hide it?

Other suggestion would be to add a timestamp next to each dot point added so it's obvious items are being added.

Love your work, thanks for your efforts.

**Comment by mdavis-xyz** [comment]
Ah, so that's why people keep asking whether I've updated the site.

Ok, I'll update the date to today.
