### ISSUE TITLE
What a list of "achievements"! Search function please

### ISSUE THREAD

**Issue by rbt14** [mdavis-xyz/mdavis.xyz#17]
My activism is running big heads of PM's (Puppet Politics on Facebook and funky_cool_dad). This list is very useful and I appreciate the effort that went into it. I was looking for a search function in the list. I found I could print/save a topic section as a PDF and the links worked. Copy paste to Word had monster link images and 450pages.
Could you please put a search function in the list?
Thanks again for your work on this.
![What crisis - no pole](https://user-images.githubusercontent.com/92829102/137998964-4cfecdad-2080-475a-bcfb-1ed8ffdd3702.png)

**Comment by mdavis-xyz** [comment]
How would a search function be different to ctrl-f and searching the page for keywords with your browser?

**Comment by rbt14** [comment]
Thank you Matthew
Matthew Armstrong
0438 125 322

**Comment by rbt14** [comment]
Hello Matthew

Not everyone will be familiar with this search function. Could you please include this information at the top of the table. It would make all the work you have done more accessible. 

Matthew

**Comment by mdavis-xyz** [comment]
A search function is non-trivial to implement, especially if you want to handle spelling errors, synonyms etc, and I'm not really a front-end developer. So this is not my strength.

Currently there's a button to group by topic. But some dots are related to multiple topics. So what if I had a list of pre-defined topics up top, and you can click to select a few of them, and it shows the ones related to those?

**Comment by mdavis-xyz** [comment]
I've added some more detailed filter options. That's the best I can do with my level of skill and spare time.

**Comment by rbt14** [comment]
Hi
I think it would be worth a try
Matthew
