### ISSUE TITLE
Loyal Wingman

### ISSUE THREAD

**Issue by ConradHollywood** [mdavis-xyz/mdavis.xyz#2]
Saw no mention, figured I should raise a ticket. Thanks for your efforts.

In July 2018, thousands of leading AI researchers signed a pledge to not help develop killer AI robots, or autonomous drones, citing a range of ethical concerns. [Source](https://www.theguardian.com/science/2018/jul/18/thousands-of-scientists-pledge-not-to-help-build-killer-ai-robots)

Despite this, the US Army announces plans that month to begin work on them. [Source](https://www.colocationamerica.com/blog/ai-army-drones)

In Feb 2019, ABC has an article on the RAAF working on a secret project with Boeing to develop them for Australia. [Source](https://www.abc.net.au/news/2019-02-27/combat-drone-secretly-developed-by-raaf-and-boeing-unveiled/10851000?nw=0)

The Loyal Wingman, a drone with the capability and intention to be fully autonomous and carry weaponry, was unveiled in May 2020, with the Prime Minister Scott Morrison calling it a "truly historic moment for our country and for Australian defence innovation". [Source](https://www.abc.net.au/news/2020-05-05/ai-attack-drone-australian-designed-prototype/12215612)

**Comment by mdavis-xyz** [comment]
Good story.

I'm trying to find more detail about the autonomous targeting system. e.g. is there automatic targetting to aim the weapon, and a human in the loop shown a view of the crosshairs pushing a button to fire? Or does the machine pull the trigger? Personally I think it's a slippery slope and the distinction doesn't matter much, but many people would consider it a big difference.

e.g. I found this article from a site I assume would not be technically accurate, and it doesn't mention weapon capability much: https://www.defensenews.com/air/2020/05/04/boeing-rolls-out-australias-first-loyal-wingman-combat-drone/

**Comment by mdavis-xyz** [comment]
Closing due to staleness.

As far as I can tell Australia's involvement doesn't include autonomous weapons.
