### ISSUE TITLE
ARC Research Grant Vetos

### ISSUE THREAD

**Issue by tommycp3** [mdavis-xyz/mdavis.xyz#20]
Can we please add the ARC research grant veto issue to the list, for more information see this tweet: 

https://twitter.com/ARC_Tracker/status/1493821964238336001

**Comment by mdavis-xyz** [comment]
I'll add [this link](https://www.theguardian.com/australia-news/2021/dec/24/federal-governments-christmas-eve-veto-of-research-projects-labelled-mccarthyism}) to the next update.
