### ISSUE TITLE
filter by impact

### ISSUE THREAD

**Issue by yoshikenn** [mdavis-xyz/mdavis.xyz#22]
Hey mate, thank you for this list! It is exhausting trying to get through it all. Heres to hoping we can soon put it behind us. 

My only thought, and maybe it is too difficult to implement,  is to sort it by impact, whether its monetary, social etc

And even have the bigger items in bold or something. This could be a very useful tool to show people in the lead up to the election. I personally know many people who seem to forget come election time all the shit from the last 8 years. 

Cheers,  Josh. Again, the work on the list is already much appreciated!

**Comment by mdavis-xyz** [comment]
Assigning an impact to most points is quite subjective. The money ones are easy, but most don't have a dollar figure.

I already highlight what I think are the most important ones in bold. Although there was a typo earlier this week, so most of the list was bold by accident.
