### ISSUE TITLE
Australia’s carbon credit scheme ‘largely a sham’, says whistleblower who tried to rein it in

### ISSUE THREAD

**Issue by amplexus** [mdavis-xyz/mdavis.xyz#23]
https://www.theguardian.com/environment/2022/mar/23/australias-carbon-credit-scheme-largely-a-sham-says-whistleblower-who-tried-to-rein-it-in

**Comment by mdavis-xyz** [comment]
Added to my local draft. Will be published soon.

**Comment by mdavis-xyz** [comment]
Thanks
