### ISSUE TITLE
Environment report not released since Dec'21 using loophole

### ISSUE THREAD

**Issue by muthijammy** [mdavis-xyz/mdavis.xyz#24]
Given, gov claims doing great on environment, why is Environment report not released since Dec'21 using loophole? There is legal mandate (Julia gilard or Rudd+Greens achievement) to release it before 15 sittings and so gov not scheduled that many in 4 months of 2022 before election.
 After koala listed endangered, this 5 yr report will be bad news that will break their lie "we are beating targets in a canter (only bocoz of LULF ) & better than most developed countries (only becoz of comparing other countries b4 COVID Vs AU with COVID)". Same done for Gladys NSW ICAC inquiry as well, will not be out till May22 elections

https://www.theguardian.com/environment/2022/apr/06/coalition-accused-of-sitting-on-environment-report-to-avoid-delivering-more-bad-news
https://www.abc.net.au/news/2021-11-01/australia-climate-change-reputation-ahead-of-cop26-warming-talks/100579386

1. AU only OECD country out of 35, not to ban 91 highly polluting petrol. Pending for a decade

2. Mandating new homes with no fire or flood risk, electric cooking & heating or EV,   its same.

3. Gov doing gas based covid recovery than renewables based recovery but we paying more than export market price for locally produced gas.

4. AU Worlds third largest fossil fuel exporter after Ruusia & saudi. 

5. More than 100 countries joined the US and EU in committing to cutting methane emissions by 30 per cent by 2030 except AU https://www.abc.net.au/news/2021-11-03/australia-refuses-to-join-global-pledge-to-cut-methane-emissions/100589510

**Comment by mdavis-xyz** [comment]
report card -adding now

1. petrol - I'm assuming you mean [this](https://www.carsguide.com.au/car-news/federal-government-considering-ban-on-regular-unleaded-fuel-49253)? I've added that now, thanks.

2. please provide more info

3. I've already got some mentions of the gas based recovery. What info is missing?

4. I've tried to list specific approvals,  policies and targets. I think that ways it's clearer what the government's contribution to that is. And I get more dots that way.

5 - already in the list

**Comment by muthijammy** [comment]
2. More NSW gov related. So leave it for now. New Building codes left out claiming it will increase house cost in favor of developer donors
3. Ok leave then
4. Ok
5. Ok

Can be closed once environment report & petrol are added

**Comment by muthijammy** [comment]
Is below covered?

Meanwhile, what gov is busy doing

 Instead of reducing 3.5 years notice needed for shutting down coal plants, proposal to increase to 5 years can be mandated before elections. Considering they can do battery operational in SA in 100 days, no need at all for it. Wish Gov works against fossil fuel like this

https://www.theguardian.com/australia-news/2022/apr/07/angus-taylor-in-pre-election-move-to-make-coal-plants-give-five-years-notice-before-closing

**Comment by mdavis-xyz** [comment]
Adding that now (should be published later today.)
