### ISSUE TITLE
Few duplicates and irrelevants like Nationals buying domain of rival candidates

### ISSUE THREAD

**Issue by muthijammy** [mdavis-xyz/mdavis.xyz#25]
Found duplicates like below:

Claimed that the federal environment minister is not responsible for climate change efforts and policy.

Also, can we irrelevant for federal gov like below:

Used bad-faith campaign tactics by purchasing web domains with political opponents names, to prevent the opponents from having a reasonable website domain. source

**Comment by mdavis-xyz** [comment]
> Claimed that the federal environment minister is not responsible for climate change efforts and policy.

Duplicated with what?
This one?

> Took children to court to argue that the environment minister is not required to consider the harm their decisions cause to young Australians via Climate Change when approving fossil fuel projects.

I think those are two distinct issues really. One is about whether the environment minister should care about the climate generally. The other is about legal action and the question of duty of care.

For the domain squatting, ah I see, that's a state issue not federal. Removing now.
