### ISSUE TITLE
795 is not true "Increased the fee for lodging Freedom of Information requests."

### ISSUE THREAD

**Issue by gitcnd** [mdavis-xyz/mdavis.xyz#29]
There is no fee to lodge an FoI.  I've lodged many.

You get what you pay for still though - if they ever answer anything (rare) it is always lies.

Fun fact: the only public servants allowed to answer FoI requests are required, by law, to be lawyers - and the requirements for being a lawyer is to always act in the best interest of your client (the government) - so the FoI requirement about releasing information even if it is embarrassing, is never possible to do, since that would break the FoI lawyers oath and legal duty in so doing.

**Comment by mdavis-xyz** [comment]
I have paid for an FOI request in the past. Although that was a NSW gov one.

https://www.oaic.gov.au/freedom-of-information/how-to-make-an-foi-request/what-charges-may-apply

> There is no charge for [access](https://www.oaic.gov.au/freedom-of-information/your-foi-rights/access-information-under-foi) to a [document](https://www.oaic.gov.au/freedom-of-information/your-foi-rights/what-is-a-document) that has your [personal information](https://www.oaic.gov.au/privacy/your-privacy-rights/your-personal-information/what-is-personal-information). However, the agency or minister who holds the document may ask you to identify yourself so they can make sure the document relates to you.

So I guess I'll change "lodging" to "processing"?

**Comment by gitcnd** [comment]
I've never been charged for any of mine (lots - all of which ended up going through multiple OAIC and other complaint processes since the government "lied their asses" off in every one - all my FoI's are aimed at revealing government corruption and ineptitude.  I even have multiple examples of the OAIC themselves conspiring with departments, lying themselves, and covering up OAIC corruption in their own ranks... but I digress... none of that cost $$$).

Try to keep everything you say totally true and honest: you only need to say one thing that's wrong, and you can guarantee that will be the thing that your opponents use to discredit *everything* you say.

If you want to claim that they increased fees - be 100% sure that they really did, and that it's relevant (e.g. CPI/inflation or whatever are not relevant).

**Comment by mdavis-xyz** [comment]
Rechecking that link I had, it doesn't really back up the claim.
So yeah I'll delete that. Thanks.
