### ISSUE TITLE
New ASIC administration costs imposed on financial companies since the coalition took power

### ISSUE THREAD

**Issue by rbfx4x** [mdavis-xyz/mdavis.xyz#3]
Hi.  
You forgot two new administration costs forced upon Australian financial companies by the coalition government.  

1) From 2015, derivatives brokers were required to report all trade data to ASIC via a privately run trade repository to which we pay more than $120,000 per year in fees.  See RG 251 for details. https://asic.gov.au/regulatory-resources/find-a-document/regulatory-guides/rg-251-derivative-transaction-reporting/
 
2) Since 2019 ASIC was moved from a government funded to industry funded model. This imposition requires a mandatory fee of over $50,000 per year for every financial services company.  https://asic.gov.au/about-asic/what-we-do/how-we-operate/asic-industry-funding/

That's more than $170,000 per year of new fees imposed on the financial services industry per year by the Coalition government.  

I am authorised to disclose that these new 6 figure fees imposed on our company has caused job losses.

**Comment by mdavis-xyz** [comment]
1. You say it's privately run, but the link says:

> ASIC is responsible for administering the derivative trade repository licensing regime

ASIC themselves aren't privatised. 

On page 5 it says:

> Division 6 of Pt 7.5A of the Corporations Act 2001 (Corporations Act) (as amended by the Corporations Legislative Amendment (Derivative Transactions) Act **2012**) contains a licensing regime for trade repositories, largely modelled on the existing licensing regimes for market operators and clearing and settlement (CS) facilities.

2012 was just before the Coalition got in. So was this a change by Labor? Was this [this bill](https://www.aph.gov.au/Parliamentary_Business/Bills_Legislation/bd/bd1213a/13bd049)?

**Comment by mdavis-xyz** [comment]
For 2, here's another relevant link. I'll pop that in too, because it makes it clearer what the change was.
https://www.cpaaustralia.com.au/professional-resources/asic-industry-funding

**Comment by mdavis-xyz** [comment]
https://asic.gov.au/regulatory-resources/find-a-document/regulatory-guides/rg-251-derivative-transaction-reporting/ - adding this link to the dot about database privatisation.
