### ISSUE TITLE
210 is not accurate - URL metadata

### ISSUE THREAD

**Issue by gitcnd** [mdavis-xyz/mdavis.xyz#30]
This statement is not accurate, not supported by the source, and also not technically possible: "Lied about data retention laws, claiming only metadata would be captured (e.g. domain name), when actually full URLs are captured, which includes detail such as the specific queries you give to Google, and specific videos you watch on PornHub."

Almost all sites visited by Australians now use TLS - a technology which makes it impossible for intermediaries to capture URLs.

The source mentions "www." something "dot com" as being captured - which is a domain-name, and NOT a URL - and it's clear from the context of the source that they're discussing domain names, and NOT URLs (even though they wrongly use the word "url" to mean, as they said, "www." something "dot com".).

To be absolutely clear - Google search terms and pornhub videos watched are absolutely not technically possible to include in metadata (since both those sites use TLS, and pornhub has deployed HSTS ("HTTP Strict Transport Security") and google even uses certificate pins and CAA ("Certification Authority Authorization") further preventing any possible attempt for intermediaries to collect URLs.

**Comment by mdavis-xyz** [comment]
Yeah this is my mistake.

The article claims that full URLs are captured. URLs do contain search queries. But the specific sites I listed are encrypted.
So I'm interpreting this is meaning that *if* a site is unencrypted, then full URLs are captured.

Note that the phrase `"www." something "dot com"` came from the committee chair, not the respondent. That chair has a bachelors of Arts, and a career as an ADF soldier. So I think we can assume he's not clear on the distinction.

When you read the response:

> multiple clicks, for example, on a thread would generate more and more, I guess, content.

That sounds like the referral tracking stuff you get in a URL after the `?`. 

e.g.
https://www.theguardian.com/australia-news/2022/apr/09/government-defends-flurry-of-appointments-to-key-roles-of-former-coalition-staffers-and-mps?utm_source=pocket_mylist
vs
https://www.theguardian.com/australia-news/2022/apr/09/government-defends-flurry-of-appointments-to-key-roles-of-former-coalition-staffers-and-mps

What could he be meaning if this is just a domain name? Just more HTTP requests? But they'd mostly be the same domain. Maybe www.something.com and api.something.com and cdn.something.com ? Or is he talking about how new analytics tools sneakily add random hex as a sub-domain which is a CNAME to the actual tracking tool, to circumvent privacy protecting browser extensions?

**Comment by mdavis-xyz** [comment]
Yeah fair enough.
I don't think this guy was talking about DNS requests. (Surely the cache hit rate for normal browsing is like 99% anyway?)
But it's likely enough that he was just saying incorrect things.
I'll delete this point. (I've got plenty of others about data retention in general anyway, I think.)

**Comment by gitcnd** [comment]
I think that's the best approach - better to be 100% sure, than risk arming opponents.

The scale of surveillance in Australia is staggering and disgusting, and littered with lies and broken promises and an order of magnitude more disreputable behaviour goes on "behind closed doors" (I've sat on a few panels and committees as an advisor).  It's a shame that so much of that is "classified" and immune to FoI and generally too complicated to clearly articulate to the general public in bullet points!

... and that's not even *starting* on foreign surveillance and the five eyes arrangements...
