### ISSUE TITLE
suggestion - archive all resources

### ISSUE THREAD

**Issue by gitcnd** [mdavis-xyz/mdavis.xyz#31]
Submitting all resources here would be an excellent idea:-
https://help.archive.org/help/save-pages-in-the-wayback-machine/

As I'm sure everyone here will not be surprised to learn... web pages that show our government in unfavourable light tend not to last for very long.

**Comment by mdavis-xyz** [comment]
Good idea.

I've got thousands of links, so I'd have to automate it.

I already automated replacing stale URLs with ones that happen to have been archived. But if they haven't been archived, I'm out of luck. (It's mostly the news sites who are the culprits here. Parliamentary stuff is usually good, but stuff for individual ministers goes stale often.)

I'm using the [wayback](https://wayback.readthedocs.io/en/stable/index.html) python library to fetch wayback URLs, but that library doesn't support creating a snapshot ("momento").
It looks like the API is pretty trivial though.

Just a GET (not even a POST?) to `"https://web.archive.org/save/"+url`.

**Comment by mdavis-xyz** [comment]
Ok, done. That was surprisingly easy. The internet archive didn't seem to throttle me when I archived a few hundreds pages in one go.
