### ISSUE TITLE
Snowy 2.0 cost 10B$ to tax payor extra,delayed completion by 150%,will increase electricity prices based on its own modelling,environment hugely impacted, less jobs only generated and will be rarely useful 

### ISSUE THREAD

**Issue by muthijammy** [mdavis-xyz/mdavis.xyz#33]
Snowy 2.0 was to be completed in four years (that is, by 2021) at a cost of $2 billion without any taxpayer subsidy, bring down electricity prices, generate renewable energy and incur minimal environmental impact on Kosciuszko National Park.Nation-building vision was for a big battery to be added & much-trumpeted construction jobs to the Monaro.

Now optimistically estimated to be completed in 2026, we will be left with a rarely used, $10 billion-plus from tax payor Snowy White Elephant, higher electricity prices based on its own modelling, a needlessly scarred Kosciuszko National Park, and just a dozen extra Snowy Hydro jobs, according to the Snowy 2.0 environmental impact statement.Despite conclusive evidence that the project is fundamentally flawed and can never pay for itself,Nsw gov & federal gov are bend over backwards with billion-dollar subsidies.

https://amp.smh.com.au/national/five-years-on-snowy-2-0-emerges-as-a-10-billion-white-elephant-20220310-p5a3ge.html

**Comment by mdavis-xyz** [comment]
non-AMP link: https://www.smh.com.au/national/five-years-on-snowy-2-0-emerges-as-a-10-billion-white-elephant-20220310-p5a3ge.html

**Comment by muthijammy** [comment]
Odd, not much recent consolidated analysis as in smh. But anyways below
should be good enough

https://www.theguardian.com/australia-news/2020/mar/28/snowy-hydro-20-will-cost-more-and-deliver-less-than-promised-30-experts-say

https://www.abc.net.au/news/2019-04-09/snowy-hydro-2.0-cost-and-timeline-blows-out/10983998

https://www.macrobusiness.com.au/2022/03/shocked-shocked-snowy-2-0-turns-10bn-black-hole/

https://reneweconomy.com.au/reprehensible-snowy-slammed-over-deal-to-use-kosciuszko-park-as-a-dump/

https://reneweconomy.com.au/snowy-2-0-will-result-coal-power-delayed-solar-storage-15997/

**Comment by mdavis-xyz** [comment]
Added, will publish later today.
