### ISSUE TITLE
Achievements of the Coalition Govt

### ISSUE THREAD

**Issue by DonnaTruran** [mdavis-xyz/mdavis.xyz#4]
Love your work.  Please keep this current for 2020 and 2021. If you could also highlight the "brand names"  for some of these stories (like Sports Rorts, RoboDebt etc....) I think will more easily identify the corruption.  There are 496 days until this Govt 'expires'.  Please keep this blog safe, secure, backed up and re-upped for the next 496 days :-)

**Comment by mdavis-xyz** [comment]
Yep, good idea

**Comment by mdavis-xyz** [comment]
Done (not published yet though.)
