### ISSUE TITLE
Add to scomos list

### ISSUE THREAD

**Issue by hyd-ho** [mdavis-xyz/mdavis.xyz#5]
Not sure if it's.already on the list but:
Forced his own department to remove gender inclusive signs from their toilets.

**Comment by mdavis-xyz** [comment]
That's not on the list.

Do you have any links to articles or anything providing more info?

**Comment by hyd-ho** [comment]
This one should suffice....
There are others, let me know if you want more!

https://www.google.com/amp/s/amp.abc.net.au/article/11462552
Cheers
Heidi

**Comment by mdavis-xyz** [comment]
Thanks for the suggestion.
I think I'll leave this one out though. It's a single piece of paper about a single bathroom. I don't really want to dilute the important things in the list like stopping nuclear disarmament, funding genocidal soldiers etc. In particular, the people who are most likely to change their views on the Coalition as a whole based on this list will probably just dig their heels in and close their tab when they see this culture wars stuff.
Note that I've already covered the bigger trans issues like the religious freedom bill.
