### ISSUE TITLE
Error regarding TPP withdrawal

### ISSUE THREAD

**Issue by Bellthorpe** [mdavis-xyz/mdavis.xyz#6]
> Kept Trans-Pacific Partnership (TPP) negotiations secret, even though it threatens the very foundations of our democracy. The leaked agreement would allow international companies to sue governments if their profits are diminished by environmental, indigenous land rights or anti-child-sweatshop laws. The TPP would give corporations many of the same rights that individuals have. There is no expiration date or separation clause, so once signed, it's here

The conditions under which investors can raise disputes against governments are not quite that simple, but that's not my point. The part about "once signed, it's here" is incorrect. Article 4 is quite clear:

Article 4 : Withdrawal
1. Any Party may withdraw from this Agreement by providing written notice of
withdrawal to the Depositary. A withdrawing Party shall simultaneously notify the other
Parties of its withdrawal through the overall contact points designated under Article 27.5
(Contact Points) of the TPP.
2. A withdrawal shall take effect six months after a Party provides written notice to the
Depositary under paragraph 1, unless the Parties agree on a different period. If a Party
withdraws, this Agreement shall remain in force for the remaining Parties.

**Comment by mdavis-xyz** [comment]
Where did you find those clauses?

At the time of writing, the text of the agreement was not public, and as far as I can tell, it's still not public.

**Comment by Bellthorpe** [comment]
As with most treaties, the text was released when it was signed. Were the text not released, the treaty would not be workable. For example, the Investor-State Dispute Settlement (ISDS) process, which allows an investor to initiate an arbitration dispute, would be unworkable if investors were not aware of the dispute provisions.

The preliminary **TPP** text was released on 5th Nov 2015.

The ‘legally scrubbed’ version was released on 26th Jan 2016.

[https://www.tpp.mfat.govt.nz/text](https://www.tpp.mfat.govt.nz/text)

The latter version was signed on 4 Feb 2016.

The **CPTPP** text was released on 21 Feb 2018 and signed on 8 Mar 2018 in Chile.

[CPTPP resources page](https://www.mfat.govt.nz/en/trade/free-trade-agreements/free-trade-agreements-in-force/comprehensive-and-progressive-agreement-for-trans-pacific-partnership-cptpp/comprehensive-and-progressive-agreement-for-trans-pacific-partnership-text-and-resources/?m=972248#search:Y3B0cHAgdGV4dA==)

On January 30, 2017, the United States notified TPP signatories of its intention to not ratify, effectively withdrawing from the TPP. 

The TPP-11 legal text is [584 pages, versus the 622 pages original ](https://www.straitstimes.com/asia/australianz/how-easy-would-it-be-for-us-to-rejoin-tpp)which included the United States. 

The CPTPP entered into force on 30 December 2018.

**Comment by mdavis-xyz** [comment]
Ok, I've updated that on my local copy. (Not yet published though.)

**Comment by mdavis-xyz** [comment]
Thanks
