### ISSUE TITLE
govlist - $10,000 cash ban never went through

### ISSUE THREAD

**Issue by Harrison-Mitchell** [mdavis-xyz/mdavis.xyz#9]
One point reads
>  Introduced a limit on cash transactions of $10,000, in a move towards a cashless society, so that it then becomes possible to have negative interest rates and have consumers pay banks to store their savings.

If I'm not mistaken that [was scrapped](https://www.smh.com.au/politics/federal/plan-for-10-000-cash-ban-dead-dead-and-dead-20201203-p56kck.html) in the end.

**Comment by mdavis-xyz** [comment]
Thanks. I've just deleted that dot from the list. (I haven't published the change yet.)
